plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.tennisleague.watch'
    compileSdk rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId 'com.tennisleague.watch'
        minSdk 26
        targetSdk rootProject.ext.targetSdkVersion
        versionCode 1
        versionName '1.0.0'
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-wearable:18.2.0'
}
